// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmogInfo.Entities;

namespace SmogInfo.Migrations
{
    [DbContext(typeof(SmogInfoContext))]
    [Migration("20180729105307_Add25Con")]
    partial class Add25Con
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmogInfo.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SmogInfo.Entities.SmogLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<decimal>("PM10Concentration");

                    b.Property<decimal>("PM25Concentration");

                    b.Property<int>("StationPointId");

                    b.HasKey("Id");

                    b.HasIndex("StationPointId");

                    b.ToTable("SmogLevels");
                });

            modelBuilder.Entity("SmogInfo.Entities.StationPoint", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("CityId");

                    b.ToTable("StationPoints");
                });

            modelBuilder.Entity("SmogInfo.Entities.SmogLevel", b =>
                {
                    b.HasOne("SmogInfo.Entities.StationPoint", "StationPoint")
                        .WithMany("SmogLevels")
                        .HasForeignKey("StationPointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmogInfo.Entities.StationPoint", b =>
                {
                    b.HasOne("SmogInfo.Entities.City", "City")
                        .WithMany("StationPoints")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
